# v3.3 board kit

esphome:
  name: office-air-gradient

esp8266:
  board: d1_mini

substitutions:
  title: "Office Air Gradient"

# Enable logging
logger:

# Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# Create a switch for safe_mode in order to flash the device
# Solution from this thread:
switch:
  - platform: safe_mode
    name: "Flash Mode (Safe Mode)"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  reboot_timeout: 10min
  # used for troubleshooting some connectivity issues

  # creates a fallback hospot
  ap:
    ssid: !secret backup_wifi_ssid
    password: !secret backup_wifi_password

captive_portal:

button:
  # this is a pressable button to home assitant
  # calibration info: 
  - platform: template
    name: "$title Run Calibration"
    id: office_button
    on_press:
      then:
        - senseair.background_calibration: senseair_co2
        - delay: 120s
        - senseair.background_calibration_result: senseair_co2

i2c:
  sda: D2
  scl: D1

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 15

display:
  - platform: ssd1306_i2c
    id: oled
    # screen size/ model speciffic the to pro kit
    model: "SH1106 128x64"
    rotation: "180"
    pages:
      - id: page1
        lambda: |-
          it.printf(0, 0, id(roboto), "CO2: %.0fppm", id(co2).state);
          it.printf(0, 15, id(roboto), "PM2.5: %.0f", id(pm25).state);
          it.printf(0, 30, id(roboto), "Humidity: %.0f%%", id(humidity).state);
          it.printf(0, 45, id(roboto), "Temp: %.0f°F", id(temp).state * (9.0/5.0) + 32.0);

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart_1
    # https://esphome.io/changelog/2023.4.0.html#uart-ids
    
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart_2
    # https://esphome.io/changelog/2023.4.0.html#uart-ids

sensor:
  - platform: sht3xd
    temperature:
      id: temp
      name: "$title Temperature"
    humidity:
      id: humidity
      name: "$title Humidity"
    address: 0x44
    update_interval: 30s

  - platform: pmsx003
    type: PMSX003
    uart_id: uart_1
    pm_1_0:
      id: pm10
      name: "$title Particulate Matter <1.0µm Concentration"
    pm_2_5:
      id: pm25
      name: "$title Particulate Matter <2.5µm Concentration"
    pm_10_0:
      id: pm100
      name: "$title Particulate Matter <10.0µm Concentration"

  - platform: senseair
    uart_id: uart_2
    # id used for the calibration button
    id: senseair_co2
    co2:
      id: co2
      name: "$title SenseAir CO2 Value"
    update_interval: 30s
